name: MCAPI Request
description: "A request for some MCAPIs"
title: Request MCAPIs for <your-mod-name>
body:
  - type: textarea
    id: symbols
    attributes:
      label: Symbols
      description: The symbols provided by the error message during linking. One symbol per line.
      placeholder: "e.g.\n?$exmapleMethod@ExampleClass@@QEAAXH@Z\n?$anotherMethod@AnotherClass@@QEAA_NXZ"
      render: text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Justification
      description: Explain what mods are you working on and why you need these MCAPIs.
      placeholder: |
        e.g. I'm working on a mod to give players starter pack on their first join. I need to access their UUID to...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Include any extra context or screenshots relating to your request.
